# Generated by Django 5.2.4 on 2025-11-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='categories',
            field=models.ManyToManyField(blank=True, to='core.category'),
        ),
    ]
