# Generated by Django 5.2.4 on 2025-11-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_establishment_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterField(
            model_name='establishment',
            name='categories',
            field=models.ManyToManyField(to='core.category'),
        ),
    ]
